use_ip = ENV['LOCAL_IP']
$script = <<SCRIPT
apt-get update
apt-get install curl -y
echo #{use_ip} registry-api | tee -a /etc/hosts
SCRIPT

Vagrant.configure("2") do |c|

  c.vm.define "register-via-recipe" do |one|
    one.vm.box = "opscode-ubuntu-12.04"
    one.vm.box_url = "https://opscode-vm-bento.s3.amazonaws.com/vagrant/virtualbox/opscode_ubuntu-12.04_chef-provisionerless.box"
    one.vm.hostname = "target01.vagrantup.com"
    one.vm.synced_folder ".", "/vagrant", disabled: true
    one.vm.network(:private_network, {:ip=>"192.168.33.72"})
    one.vm.provider :virtualbox do |p|
      p.customize ["modifyvm", :id, "--memory", "256"]
    end
  end

  c.vm.define "register-via-api" do |two|
    two.vm.box = "opscode-ubuntu-12.04"
    two.vm.box_url = "https://opscode-vm-bento.s3.amazonaws.com/vagrant/virtualbox/opscode_ubuntu-12.04_chef-provisionerless.box"
    two.vm.hostname = "target02.vagrantup.com"
    two.vm.synced_folder ".", "/vagrant"
    two.vm.network(:private_network, {:ip=>"192.168.33.73"})
    two.vm.provision "shell", inline: $script
    two.vm.provision "shell", inline: "/vagrant/register_with_api.sh"
    #two.vm.provision "shell", inline: "/vagrant/setup_vagrant_vm.sh"
    two.vm.provider :virtualbox do |p|
      p.customize ["modifyvm", :id, "--memory", "256"]
    end
  end

end
