use_ip = ENV['LOCAL_IP']
$script = <<SCRIPT
apt-get update
apt-get install curl -y
echo #{use_ip} registry-api | tee -a /etc/hosts
SCRIPT

Vagrant.configure("2") do |c|

  c.vm.define "app-recipe" do |one|
    one.vm.box = "opscode-ubuntu-12.04"
    one.vm.hostname = "app-recipe.vagrantup.com"
    one.vm.synced_folder ".", "/vagrant", disabled: true
    one.vm.network(:private_network, {:ip=>"192.168.33.72"})
    one.vm.provider :virtualbox do |p|
      p.customize ["modifyvm", :id, "--memory", "256"]
    end
  end

  c.vm.define "lb" do |two|
    two.vm.box = "opscode-ubuntu-12.04"
    two.vm.hostname = "target02.vagrantup.com"
    two.vm.synced_folder ".", "/vagrant"
    two.vm.network(:private_network, {:ip=>"192.168.33.73"})
    two.vm.provision "shell", inline: $script
    two.vm.provision "shell", inline: "/vagrant/register_with_api.sh lb_server"
    two.vm.provider :virtualbox do |p|
      p.customize ["modifyvm", :id, "--memory", "256"]
    end
  end

  c.vm.define "app" do |three|
    three.vm.box = "opscode-ubuntu-12.04"
    three.vm.hostname = "app.vagrantup.com"
    three.vm.synced_folder ".", "/vagrant"
    three.vm.network(:private_network, {:ip=>"192.168.33.74"})
    three.vm.provision "shell", inline: $script
    three.vm.provision "shell", inline: "/vagrant/register_with_api.sh app_server"
    three.vm.provider :virtualbox do |p|
      p.customize ["modifyvm", :id, "--memory", "1024"]
    end
  end

  c.vm.define "db" do |four|
    four.vm.box = "opscode-ubuntu-12.04"
    four.vm.hostname = "db.vagrantup.com"
    four.vm.synced_folder ".", "/vagrant"
    four.vm.network(:private_network, {:ip=>"192.168.33.75"})
    four.vm.provision "shell", inline: $script
    four.vm.provision "shell", inline: "/vagrant/register_with_api.sh db_server"
    four.vm.provider :virtualbox do |p|
      p.customize ["modifyvm", :id, "--memory", "512"]
    end
  end

  c.vm.define "cache" do |five|
    five.vm.box = "opscode-ubuntu-12.04"
    five.vm.hostname = "cache.vagrantup.com"
    five.vm.synced_folder ".", "/vagrant"
    five.vm.network(:private_network, {:ip=>"192.168.33.76"})
    five.vm.provision "shell", inline: $script
    five.vm.provision "shell", inline: "/vagrant/register_with_api.sh cache_server"
    five.vm.provider :virtualbox do |p|
      p.customize ["modifyvm", :id, "--memory", "256"]
    end
  end

end
